---
abstract: 'common helper classes for mpd'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla version 1.092680'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-MPD-Common
provides:
  Audio::MPD::Common:
    file: lib/Audio/MPD/Common.pm
    version: 1.092830
  Audio::MPD::Common::Item:
    file: lib/Audio/MPD/Common/Item.pm
    version: 1.092830
  Audio::MPD::Common::Item::Directory:
    file: lib/Audio/MPD/Common/Item/Directory.pm
    version: 1.092830
  Audio::MPD::Common::Item::Playlist:
    file: lib/Audio/MPD/Common/Item/Playlist.pm
    version: 1.092830
  Audio::MPD::Common::Item::Song:
    file: lib/Audio/MPD/Common/Item/Song.pm
    version: 1.092830
  Audio::MPD::Common::Stats:
    file: lib/Audio/MPD/Common/Stats.pm
    version: 1.092830
  Audio::MPD::Common::Status:
    file: lib/Audio/MPD/Common/Status.pm
    version: 1.092830
  Audio::MPD::Common::Time:
    file: lib/Audio/MPD/Common/Time.pm
    version: 1.092830
requires:
  English: 0
  File::Find: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Readonly: 0
  Test::More: 0
  base: 0
  overload: 0
resources:
  homepage: http://search.cpan.org/dist/Audio-MPD-Common
  repository: http://github.com/jquelin/audio-mpd-common
version: 1.092830
