---
abstract: 'common helper classes for mpd'
author:
  - 'Jerome Quelin'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-MPD-Common
provides:
  Audio::MPD::Common:
    file: lib/Audio/MPD/Common.pm
    version: 1.100430
  Audio::MPD::Common::Item:
    file: lib/Audio/MPD/Common/Item.pm
    version: 1.100430
  Audio::MPD::Common::Item::Directory:
    file: lib/Audio/MPD/Common/Item/Directory.pm
    version: 1.100430
  Audio::MPD::Common::Item::Playlist:
    file: lib/Audio/MPD/Common/Item/Playlist.pm
    version: 1.100430
  Audio::MPD::Common::Item::Song:
    file: lib/Audio/MPD/Common/Item/Song.pm
    version: 1.100430
  Audio::MPD::Common::Stats:
    file: lib/Audio/MPD/Common/Stats.pm
    version: 1.100430
  Audio::MPD::Common::Status:
    file: lib/Audio/MPD/Common/Status.pm
    version: 1.100430
  Audio::MPD::Common::Time:
    file: lib/Audio/MPD/Common/Time.pm
    version: 1.100430
  Audio::MPD::Common::Types:
    file: lib/Audio/MPD/Common/Types.pm
    version: 1.100430
requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0.92
  Moose::Util::TypeConstraints: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  Readonly: 0
  Test::More: 0
  overload: 0
  perl: 5.008
resources:
  MailingList: http://groups.google.com/group/audio-mpd
  homepage: http://search.cpan.org/dist/Audio-MPD-Common
  repository: http://github.com/jquelin/audio-mpd-common
version: 1.100430
